export const DEFAULT_STAGE_SETTINGS = {
  enemyTypes: ["Kappa"],
  bossType: "KappaOyabun",
  enemyLevel: null,
  enemyRank: null,
  bossRank: null,
};
/*  {
    id: 12,
    enemyLevel: 12,
    enemyRank: 3,
    bossRank: 4,
    enemyTypes: ["Genin"],
    bossType: "Genin",
  }
*/
export const STAGE_CONFIGS = {
  N1: [],
  N2: [],
  N3: [],
  N4: [],
  N5: [
    { id: 1,
      name: "numbers",
      files: ["N5_stage1.json"],
      bgKey: "stage_1",
      enemyLevel: 1,
      enemyTypes: ["Kappa"],
      bossType: "KappaOyabun",
    },
    { id: 2,
      name: "times of days",
      files: ["N5_stage2.json"],
      bgKey: "stage_2",
      enemyLevel: 2,
      enemyTypes: ["Kappa"],
      bossType: "KappaOyabun",
    },
    { id: 3,
      name: "dates & years",
      files: ["N5_stage3.json"],
      bgKey: "stage_3",
      enemyLevel: 3,
      enemyTypes: ["Kappa"],
      bossType: "KappaOyabun",
    },
    { id: 4,
      name: "days of the week",
      files: ["N5_stage4.json"],
      bgKey: "stage_4",
      enemyLevel: 4,
      enemyTypes: ["Kappa","OneEyedGoblin"],
      bossType: "KappaOyabun",
    },
    { id: 5,
      name: "family",
      files: ["N5_stage5.json"],
      bgKey: "stage_5",
      enemyLevel: 5,
      enemyTypes: ["Kappa","OneEyedGoblin"],
      bossType: "OneEyedGoblinOyabun",
    },
    { id: 6,
      name: "people & identity",
      files: ["N5_stage6.json"],
      bgKey: "stage_6",
      enemyLevel: 6,
      enemyTypes: ["Kappa","OneEyedGoblin"],
      bossType: "OneEyedGoblinOyabun",
    },
    { id: 7,
      name: "colors",
      files: ["N5_stage7.json"],
      bgKey: "stage_7",
      enemyLevel: 7,
      enemyTypes: ["OneEyedGoblinOyabun","OneEyedGoblin"],
      bossType: "Oogama",
    },
    { id: 8,
      name: "nature & seasons",
      files: ["N5_stage8.json"],
      bgKey: "stage_8",
      enemyLevel: 8,
      enemyTypes: ["OneEyedGoblinOyabun","KappaOyabun"],
      bossType: "Oogama",
    },
    { id: 9,
      name: "transport",
      files: ["N5_stage9.json"],
      bgKey: "stage_9",
      enemyLevel: 9,
      enemyTypes: ["OneEyedGoblinOyabun","KappaOyabun", "Oogama"],
      bossType: "ObakeKinoko",
    },
    { id: 10,
      name: "services & daily life",
      files: ["N5_stage10.json"],
      bgKey: "stage_10",
      enemyLevel: 10,
      enemyTypes: ["Oogama"],
      bossType: "Kakashi",
    },
    { id: 11,
      name: "Infrastructure & Commerce",
      files: ["N5_stage11.json"],
      bgKey: "stage_11",
      enemyLevel: 11,
      enemyTypes: ["ObakeKinoko","Oogama"],
      bossType: "Kakashi",
    },
    { id: 12,
      name: "Ingredients & Basic Foods",
      files: ["N5_stage12.json"],
      bgKey: "stage_12",
      enemyLevel: 12,
      enemyTypes: ["Genin"],
      bossType: "Genin",
    },
    { id: 13,
      name: "Meals & Beverages",
      files: ["N5_stage13.json"],
      bgKey: "stage_13",
      enemyLevel: 13,
      enemyTypes: ["Genin","Oogama"],
      bossType: "Genin",
    },
    { id: 14,
      name: "Jobs & Roles",
      files: ["N5_stage14.json"],
      bgKey: "stage_14",
      enemyLevel: 14,
      enemyTypes: ["Genin","Oogama"],
      bossType: "Kamaitachi",
    },
    { id: 15,
      name: "Household Items & Appliances",
      files: ["N5_stage15.json"],
      bgKey: "stage_15",
      enemyLevel: 15,
      enemyTypes: ["Genin","Oogama"],
      bossType: "Kamaitachi",
    },
    { id: 16,
      name: "House Structure & Rooms",
      files: ["N5_stage16.json"],
      bgKey: "stage_16",
      enemyLevel: 16,
      enemyTypes: ["Genin","Oogama","KappaOyabun","OneEyedGoblinOyabun"],
      bossType: "KoganeKozou",
    },
    { id: 17,
      name: "Study Materials & Tools",
      files: ["N5_stage17.json"],
      bgKey: "stage_17",
      enemyLevel: 17,
      enemyTypes: ["KappaOyabun","OneEyedGoblinOyabun"],
      bossType: "AkaOni",
    }, 
    { id: 18,
      name: "Learning & Activities",
      files: ["N5_stage18.json"],
      bgKey: "stage_18",
      enemyLevel: 18,
      enemyTypes: ["AoOni"],
      bossType: "AkaOni",
    },
    { id: 19,
      name: "Body Parts & Sensory",
      files: ["N5_stage19.json"],
      bgKey: "stage_19",
      enemyLevel: 19,
      enemyTypes: ["AoOni","AkaOni"],
      bossType: "OoOni",
    },


    ////////////////////////////
    /////      動詞
    ////////////////////////////'
    { id: 20,
      name: "Daily Life & Basic Actions",
      files: ["N5_stage20.json"],
      bgKey: "stage_20",
      enemyLevel: 20,
      enemyTypes: ["NoroiMusha"],
      bossType: "OoOni",
    },
    { id: 21,
      name: "Meals, Sleep, Chores & Personal Care",
      files: ["N5_stage21.json"],
      bgKey: "stage_21",
      enemyLevel: 21,
      enemyTypes: ["NoroiMusha"],
      bossType: "OoOni",
    },
    { id: 22,
      name: "Movement & Direction",
      files: ["N5_stage22.json"],
      bgKey: "stage_22",
      enemyLevel: 22,
      enemyTypes: ["NoroiMusha"],
      bossType: "OoOni",
    },
    { id: 23,
      name: "Communication, Thinking & Senses",
      files: ["N5_stage23.json"],
      bgKey: "stage_23",
      enemyLevel: 23,
      enemyTypes: ["NoroiMusha","HitotsumeKomori"],
      bossType: "OoOni",
    },
    { id: 24,
      name: "Object Manipulation & Changes of State",
      files: ["N5_stage24.json"],
      bgKey: "stage_24",
      enemyLevel: 24,
      enemyTypes: ["HitotsumeKomori"],
      bossType: "Tengu",
    },
    { id: 25,
      name: "Clothing, Natural Phenomena & Others",
      files: ["N5_stage25.json"],
      bgKey: "stage_25",
      enemyLevel: 25,
      enemyTypes: ["HitotsumeKomori","NoroiMusha","KappaOyabun"],
      bossType: "Tengu",
    },


    ////////////////////////////
    /////      形容詞
    ////////////////////////////'
    { id: 26,
      name: "Sensory & Physical Properties",
      files: ["N5_stage26.json"],
      bgKey: "stage_26",
      enemyLevel: 26,
      enemyTypes: ["Ashigaru"],
      bossType: "SamuraiTaishou",
    },
    { id: 27,
      name: "Size, Quantity, Time & Value",
      files: ["N5_stage27.json"],
      bgKey: "stage_27",
      enemyLevel: 27,
      enemyTypes: ["Ashigaru"],
      bossType: "SamuraiTaishou",
    },
    { id: 28,
      name: "Conditions, Feelings & Experiences",
      files: ["N5_stage28.json"],
      bgKey: "stage_28",
      enemyLevel: 28,
      enemyTypes: ["Ashigaru"],
      bossType: "SamuraiTaishou",
    },
    { id: 29,
      name: "Na-Adjectives",
      files: ["N5_stage29.json"],
      bgKey: "stage_29",
      enemyLevel: 29,
      enemyTypes: ["IwaAtama"],
      bossType: "OoZaru",
    },


    ////////////////////////////
    /////      副詞
    ////////////////////////////
    { id: 30,
      name: "Adverbs",
      files: ["N5_stage30.json"],
      bgKey: "stage_30",
      enemyLevel: 30,
      enemyTypes: ["Youko"],
      bossType: "OoZaru",
    },


    ////////////////////////////
    /////      代名詞
    ////////////////////////////
    { id: 31,
      name: "Pronouns",
      files: ["N5_stage31.json"],
      bgKey: "stage_31",
      enemyLevel: 31,
      enemyTypes: ["Youko"],
      bossType: "HitokuiBana",
    },


    ////////////////////////////
    /////      助詞
    ////////////////////////////
    { id: 32,
      name: "は vs が",
      files: ["N5_stage32.json"],
      bgKey: "stage_32",
      enemyLevel: 32,
      enemyTypes: ["PhantomDeer"],
      bossType: "ShiroOni",
    },
    { id: 33,
      name: "と vs の vs も",
      files: ["N5_stage33.json"],
      bgKey: "stage_33",
      enemyLevel: 33,
      enemyTypes: ["PhantomDeer"],
      bossType: "ShiroOni",
    },
    { id: 34,
      name: "に vs へ vs で vs や",
      files: ["N5_stage34.json"],
      bgKey: "stage_34",
      enemyLevel: 34,
      enemyTypes: ["PhantomDeer"],
      bossType: "ShiroOni",
    },

  ],
};

export const STORY_STAGE_ORDER = [
  { category: "N5", stageId: 1 },
  { category: "N5", stageId: 2 },
  { category: "N5", stageId: 3 },
  { category: "N5", stageId: 4 },
  { category: "N5", stageId: 5 },
  { category: "N5", stageId: 6 },
  { category: "N5", stageId: 7 },
  { category: "N5", stageId: 8 },
  { category: "N5", stageId: 9 },
  { category: "N5", stageId: 10 },
  { category: "N5", stageId: 11 },
  { category: "N5", stageId: 12 },
  { category: "N5", stageId: 13 },
  { category: "N5", stageId: 14 },
  { category: "N5", stageId: 15 },
  { category: "N5", stageId: 16 },
  { category: "N5", stageId: 17 },
  { category: "N5", stageId: 18 },
  { category: "N5", stageId: 19 },
  { category: "N5", stageId: 20 },
  { category: "N5", stageId: 21 },
  { category: "N5", stageId: 22 },
  { category: "N5", stageId: 23 },
  { category: "N5", stageId: 24 },
  { category: "N5", stageId: 25 },
  { category: "N5", stageId: 26 },
  { category: "N5", stageId: 27 },
  { category: "N5", stageId: 28 },
  { category: "N5", stageId: 29 },
  { category: "N5", stageId: 30 },
  { category: "N5", stageId: 31 },
  { category: "N5", stageId: 32 },
  { category: "N5", stageId: 33 },
  { category: "N5", stageId: 34 },
];

export function findStageConfig(category, stageId) {
  const stage = STAGE_CONFIGS[category]?.find((item) => item.id === stageId);
  if (!stage) return null;

  return {
    ...DEFAULT_STAGE_SETTINGS,
    ...stage,
    category,
    stageId: stage.id,
  };
}

export function getStoryStage(index) {
  const entry = STORY_STAGE_ORDER[index];
  if (!entry) return null;

  return findStageConfig(entry.category, entry.stageId);
}
